const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/pages/color.astro');
let c = fs.readFileSync(filePath, 'utf8');

c = c.replace(/        <div\s*\n\s*<!-- Instruction Box -->/g, '        <!-- Instruction Box -->');
c = c.replace(/        <div\s*\n\s*<!-- Collapsible Explanation -->/g, '        <!-- Collapsible Explanation -->');

c = c.replace(/^class="(my-6 flex[^"]+)">/gm, '        <div class="$1">');
c = c.replace(/^class="(mt-5 flex[^"]+)">/gm, '        <div class="$1">');

c = c.replace(/(<!-- Instruction Box -->[\s\S]*?<\/div>\s*)\n\s*<!-- Instruction Box -->[\s\S]*?<\/div>/g, '$1');

c = c.replace(/(<!-- Collapsible Explanation -->[\s\S]*?<\/details>\s*)\n\s*<!-- Collapsible Explanation -->[\s\S]*?<\/details>/g, '$1');

while (c.match(/<!-- Collapsible Explanation -->[\s\S]*?<\/details>\s*\n\s*<!-- Collapsible Explanation -->/)) {
  c = c.replace(/(<!-- Collapsible Explanation -->[\s\S]*?<\/details>\s*)\n\s*<!-- Collapsible Explanation -->[\s\S]*?<\/details>/g, '$1');
}

c = c.replace(/\n\s*<\/a>\s*\n\s*<\/a>\s*\n\s*<\/a>/g, '\n      </a>');
c = c.replace(/\n\s*<\/a>\s*\n\s*<\/a>/g, '\n      </a>');

c = c.replace(
  /(<div class="text-\[10px\] text-slate-400 font-bold uppercase tracking-wider text-center">Drag slider to shift background color! 🎛️<\/div>\s*)<\/div>\s*\n\s*<!-- Experiment 7:/,
  '$1        <div class="mt-5 flex items-center justify-between border-t border-slate-850 pt-4">\n          <span class="text-xs font-black text-purple-400 group-hover:text-purple-300 transition-colors">Explore &rarr;</span>\n        </div>\n      </a>\n\n      <!-- Experiment 7:'
);

c = c.replace(
  /(<div class="text-\[10px\] text-slate-400 font-bold uppercase tracking-wider text-center">3D depth from pure color — no shading needed! 🕶️<\/div>\s*)<\/div>/,
  '$1        <div class="mt-5 flex items-center justify-between border-t border-slate-850 pt-4">\n          <span class="text-xs font-black text-purple-400 group-hover:text-purple-300 transition-colors">Explore &rarr;</span>\n        </div>\n      </a>'
);

c = c.replace('7 COLOR ILLUSION EXPERIMENTS', '8 COLOR ILLUSION EXPERIMENTS');
c = c.replace(
  'title="Color & Colour Optical Illusions — 7 Visual Experiments',
  'title="Color & Colour Optical Illusions — 8 Visual Experiments'
);

c = c.replace(
  'class="relative overflow-hidden py-16 px-4 sm:px-6 lg:px-8 bg-gradient-to-b from-slate-900 via-purple-950 to-slate-950 text-white',
  'class="relative overflow-hidden py-16 px-4 sm:px-6 lg:px-8 bg-gradient-to-b from-slate-100 via-purple-50 to-white dark:from-slate-900 dark:via-purple-950 dark:to-slate-950 text-slate-900 dark:text-white'
);
c = c.replace('text-slate-200 font-medium leading-relaxed', 'text-slate-600 dark:text-slate-200 font-medium leading-relaxed');
c = c.replace('font-display text-3xl sm:text-4xl font-black text-white', 'font-display text-3xl sm:text-4xl font-black text-slate-900 dark:text-white');
c = c.replace('text-slate-400 max-w-md mx-auto text-sm', 'text-slate-600 dark:text-slate-400 max-w-md mx-auto text-sm');

// Card backgrounds for light mode
c = c.replace(/bg-slate-900\/60 border border-slate-800/g, 'bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800');
c = c.replace(/font-display text-xl font-bold text-white/g, 'font-display text-xl font-bold text-slate-900 dark:text-white');
c = c.replace(/text-slate-300 text-xs/g, 'text-slate-600 dark:text-slate-300 text-xs');

// Honest afterimage text
c = c.replace(
  '<p class="text-[10px] font-bold text-purple-600 uppercase tracking-wider animate-pulse">You\'re seeing a red afterimage! 🔮</p>',
  '<p class="text-[10px] font-bold text-slate-600 uppercase tracking-wider">If you see a ghost image, it is generated by your retina — not drawn here.</p>'
);

fs.writeFileSync(filePath, c);
console.log('color.astro patched successfully');
